#!/usr/bin/env python3
"""
Extract Knowledge Items (KIs) from failure patterns.

This script identifies recurring failure patterns and transforms them 
into markdown Knowledge Items for future AI/human reference.
"""

import json
from pathlib import Path
from collections import Counter
from datetime import datetime
import argparse

def load_failures(training_data_dir: Path):
    """Load failure data from JSONL file."""
    failures_file = training_data_dir / "failures.jsonl"
    if not failures_file.exists():
        return []
    
    failures = []
    with open(failures_file, 'r') as f:
        for line in f:
            if line.strip():
                failures.append(json.loads(line))
    return failures

def extract_knowledge_items(failures):
    """Group failures by pattern and extract solutions."""
    patterns = {}
    for failure in failures:
        pattern = failure["learning_value"]["pattern"]
        if pattern not in patterns:
            patterns[pattern] = {
                "count": 0,
                "symptoms": set(),
                "root_causes": set(),
                "solutions": set(),
                "category": failure["learning_value"]["category"],
                "last_detected": failure.get("timestamp", datetime.now().isoformat())
            }
        
        patterns[pattern]["count"] += 1
        patterns[pattern]["symptoms"].add(failure["error_details"]["symptoms"])
        patterns[pattern]["root_causes"].add(failure["error_details"]["root_cause"])
        patterns[pattern]["solutions"].add(failure["recovery"]["resolution"])
        if failure.get("timestamp", "") > patterns[pattern]["last_detected"]:
            patterns[pattern]["last_detected"] = failure["timestamp"]
            
    return patterns

def save_ki_files(patterns, ki_dir: Path):
    """Save each pattern as a Markdown Knowledge Item."""
    ki_dir.mkdir(parents=True, exist_ok=True)
    
    for pattern_name, data in patterns.items():
        # Sanitize filename
        safe_name = pattern_name.lower().replace(" ", "_").replace("/", "_")
        ki_file = ki_dir / f"{safe_name}.md"
        
        content = [
            f"# KI: {pattern_name}",
            f"",
            f"> **Category**: {data['category']}",
            f"> **Frequency**: {data['count']} occurrences",
            f"> **Last Detected**: {data['last_detected']}",
            f"",
            f"## 🔍 Symptoms",
            f"",
        ]
        
        for symptom in data["symptoms"]:
            content.append(f"- {symptom}")
            
        content.extend([
            f"",
            f"## 🧬 Root Causes",
            f"",
        ])
        
        for cause in data["root_causes"]:
            content.append(f"- {cause}")
            
        content.extend([
            f"",
            f"## ✅ Verified Solutions",
            f"",
        ])
        
        for solution in data["solutions"]:
            content.append(f"- {solution}")
            
        content.extend([
            f"",
            f"---",
            f"*Generated by ADDS KI Extraction Tool on {datetime.now().strftime('%Y-%m-%d')}*"
        ])
        
        with open(ki_file, 'w') as f:
            f.write('\n'.join(content))
            
    return len(patterns)

def main():
    parser = argparse.ArgumentParser(description="Extract KIs from ADDS failures")
    parser.add_argument('--project-dir', type=Path, default=Path.cwd())
    args = parser.parse_args()
    
    data_dir = args.project_dir / ".ai" / "training_data"
    ki_dir = args.project_dir / "docs" / "KNOWLEDGE_ITEMS"
    
    failures = load_failures(data_dir)
    if not failures:
        print("No failures found for extraction.")
        return
        
    patterns = extract_knowledge_items(failures)
    num_ki = save_ki_files(patterns, ki_dir)
    
    print(f"Extracted {num_ki} Knowledge Items to {ki_dir}")

if __name__ == "__main__":
    main()
